const collections = {
  late: [['Masala dosa', 'Dosa Department · 11–17 min', 139, '🥞'], ['Spicy schezwan noodles', 'Noodle Theory · 12–18 min', 189, '🍜'], ['Crispy veg momos', 'Noodle Theory · 12–18 min', 149, '🥟'], ['Vada pav duo', 'The Corner Market · 10–15 min', 99, '🍔'], ['Masala chai', 'Northside Coffee · 8–12 min', 99, '🍵'], ['Gulab jamun', 'Noodle Theory · 12–18 min', 79, '🍮'], ['Paneer paratha', 'Ghar Ka Tiffin · 14–19 min', 149, '🫓'], ['Mango lassi', 'Fresh Press · 7–12 min', 119, '🥭']],
  study: [['Cold coffee', 'Northside Coffee · 8–12 min', 129, '☕'], ['Paneer sandwich', 'Northside Coffee · 8–12 min', 159, '🥪'], ['Peanut butter shake', 'Fresh Press · 7–12 min', 149, '🥤'], ['Aloo bhujia namkeen', 'Campus Pantry · 10–15 min', 65, '🥨'], ['Chocolate brownie', 'Northside Coffee · 8–12 min', 119, '🍫'], ['Fruit chaat', 'Fresh Press · 7–12 min', 119, '🍎'], ['Instant coffee sachets', 'Campus Pantry · 10–15 min', 99, '☕'], ['Trail mix', 'The Corner Market · 10–15 min', 159, '🥜']],
  pantry: [['Maggi 6-pack', 'Campus Pantry · 10–15 min', 129, '🍜'], ['Amul Taaza milk', 'Campus Pantry · 10–15 min', 68, '🥛'], ['Aloo bhujia namkeen', 'Campus Pantry · 10–15 min', 65, '🥨'], ['Parle-G biscuit pack', 'Campus Pantry · 10–15 min', 55, '🍪'], ['Bread loaf', 'Campus Pantry · 10–15 min', 48, '🍞'], ['Banana bunch', 'Campus Pantry · 10–15 min', 59, '🍌'], ['Cold drink trio', 'Campus Pantry · 10–15 min', 99, '🥤'], ['Breakfast rescue', 'Campus Pantry · 10–15 min', 189, '🥣']],
  forgot: [['USB-C charging cable', 'QuickStop Market · 8–12 min', 499, '🔌'], ['Late-night essentials', 'QuickStop Market · 8–12 min', 249, '🪥'], ['First aid mini-kit', 'QuickStop Market · 8–12 min', 199, '🩹'], ['Power bank', 'QuickStop Market · 8–12 min', 899, '🔋'], ['Shower reset kit', 'QuickStop Market · 8–12 min', 299, '🧴'], ['Notebooks 3-pack', 'QuickStop Market · 8–12 min', 149, '📓'], ['Blue ball pens', 'QuickStop Market · 8–12 min', 59, '🖊️'], ['ORS hydration pack', 'QuickStop Market · 8–12 min', 60, '💧']]
};
const items = collections[document.body.dataset.category];
const productGrid = document.querySelector('.category-grid-products');
const bag = JSON.parse(localStorage.getItem('dashmate-items') || '[]');
function updateBag() { const count = bag.reduce((sum, item) => sum + item.quantity, 0); document.querySelector('.shop-cart-count').textContent = count; document.querySelector('.shop-cart strong').textContent = `${count} item${count === 1 ? '' : 's'} in your bag`; localStorage.setItem('dashmate-items', JSON.stringify(bag)); }
function renderProducts() { productGrid.innerHTML = items.map(([name, details, price, icon]) => { const active = bag.some((item) => item.name === name); return `<article class="product-card"><span class="product-emoji">${icon}</span><div><h3>${name}</h3><p>${details}</p><strong>₹${price.toFixed(2)}</strong></div><button class="product-add ${active ? 'remove-product' : ''}" data-name="${name}" data-price="${price}" data-added="${active}">${active ? '− Remove' : '+ Add'}</button></article>`; }).join(''); document.querySelector('.category-count').textContent = `${items.length} picks`; }
productGrid.addEventListener('click', (event) => { if (!event.target.classList.contains('product-add')) return; const button = event.target; const index = bag.findIndex((item) => item.name === button.dataset.name); if (button.dataset.added === 'true') { if (index > -1) { bag[index].quantity -= 1; if (bag[index].quantity < 1) bag.splice(index, 1); } button.dataset.added = 'false'; button.textContent = '+ Add'; button.classList.remove('remove-product'); } else { if (index > -1) bag[index].quantity += 1; else bag.push({ name: button.dataset.name, price: Number(button.dataset.price), quantity: 1, store: button.dataset.name, icon: '🛍️' }); button.dataset.added = 'true'; button.textContent = '− Remove'; button.classList.add('remove-product'); } updateBag(); });
document.querySelector('.category-search input').addEventListener('input', (event) => { const query = event.target.value.toLowerCase(); productGrid.querySelectorAll('.product-card').forEach((card) => { card.hidden = query && !card.textContent.toLowerCase().includes(query); }); });
renderProducts(); updateBag();
