const storedItems = JSON.parse(localStorage.getItem('dashmate-items') || '[]');
const countEl = document.querySelector('.shop-cart-count');
const labelEl = document.querySelector('.shop-cart strong');
const indianPrices = { 'Dorm snack restock': 179, 'Instant noodle 6-pack': 129, 'Cold drink trio': 99, 'Fresh fruit cup': 79, 'Breakfast rescue': 189, 'Study night ice cream': 149, 'Late-night essentials': 249, 'USB-C charging cable': 499, 'First aid mini-kit': 199, 'Shower reset kit': 299, 'Power bank': 899, 'Room refresh bundle': 219 };
const extraProducts = document.body.classList.contains('pantry-page') ? [
	['Aloo bhujia namkeen', 'Classic spicy sev snack, 200 g', 65, '🥨'], ['Parle-G biscuit pack', 'Tea-time classic, family pack', 55, '🍪'], ['Masala Maggi 6-pack', 'Six packs of masala noodles', 129, '🍜'], ['Amul Taaza milk', 'Fresh toned milk, 1 litre', 68, '🥛'], ['Curd tub', 'Fresh dahi, 400 g', 55, '🥣'], ['Bread loaf', 'Soft sandwich bread', 48, '🍞'], ['Peanut butter', 'Creamy spread, 340 g', 189, '🥜'], ['Kelloggs corn flakes', 'Crunchy breakfast cereal', 199, '🥣'], ['Banana bunch', 'Six ripe bananas', 59, '🍌'], ['Apple pack', 'Four crisp Shimla apples', 149, '🍎'], ['Coconut water', 'Two chilled tetra packs', 119, '🥥'], ['Lemon soda cans', 'Three refreshing cans', 105, '🥤'], ['Kurkure masala pack', 'Two crunchy snack packs', 60, '🟡'], ['Dark chocolate', '55% cocoa bar', 110, '🍫'], ['Instant coffee sachets', 'Ten sachets for late-night study', 99, '☕'], ['Green tea bags', 'Twenty calming tea bags', 125, '🍵'], ['Cooking oil pouch', 'Sunflower oil, 500 ml', 89, '🫗'], ['Rice bowl cups', 'Two ready-to-eat rice bowls', 139, '🍚'], ['Mango drink', 'Two chilled mango drinks', 90, '🧃'], ['Ice cubes', 'Food-safe ice, 1 kg', 45, '🧊']
] : [
	['Shampoo sachet bundle', 'Ten everyday shampoo sachets', 75, '🧴'], ['Face wash', 'Oil-control face wash, 100 g', 199, '🫧'], ['Sanitary care pack', 'Comfort pads, eight count', 149, '🌸'], ['Hand sanitiser', 'Pocket sanitiser, 100 ml', 79, '🧴'], ['Toothbrush duo', 'Two soft-bristle toothbrushes', 119, '🪥'], ['Laundry detergent', 'Easy-wash detergent, 500 g', 129, '🧺'], ['Fabric conditioner', 'Fresh linen conditioner', 169, '🌿'], ['Mosquito repellent', 'Overnight protection refill', 189, '🦟'], ['Notebooks 3-pack', 'College ruled notebooks', 149, '📓'], ['Blue ball pens', 'Smooth writing, five pack', 59, '🖊️'], ['Highlighter set', 'Four study-color highlighters', 129, '🖍️'], ['Sticky notes', 'Bright 3 x 3 inch notes', 69, '🗒️'], ['Earphones', 'Wired in-ear earphones', 299, '🎧'], ['AA battery pair', 'Reliable alkaline batteries', 89, '🔋'], ['LED study bulb', 'Warm white 9W bulb', 199, '💡'], ['Rain poncho', 'Compact emergency poncho', 129, '🌧️'], ['Pain relief balm', 'Cooling balm, 25 g', 99, '🧪'], ['ORS hydration pack', 'Four lemon hydration sachets', 60, '💧'], ['Protein bar', 'Chocolate peanut energy bar', 89, '🍫'], ['Paper cups', 'Twenty disposable paper cups', 79, '🥤']
];
extraProducts.forEach(([name, description, price, icon]) => { indianPrices[name] = price; const card = document.createElement('article'); card.className = 'product-card'; card.innerHTML = `<span class="product-emoji">${icon}</span><div><h3>${name}</h3><p>${description}</p><strong>₹${price.toFixed(2)}</strong></div><button class="product-add" data-name="${name}" data-price="${price}">+ Add</button>`; document.querySelector('.product-grid').appendChild(card); });
document.querySelector('.product-count').textContent = `${6 + extraProducts.length} items`;
const productSearch = document.createElement('div');
productSearch.className = 'storefront-search';
productSearch.innerHTML = '<span>⌕</span><input type="search" aria-label="Search products" placeholder="Search groceries, essentials, and more" /><kbd>⌘ K</kbd>';
document.querySelector('.shop-products').insertBefore(productSearch, document.querySelector('.product-grid'));
productSearch.querySelector('input').addEventListener('input', (event) => {
	const query = event.target.value.toLowerCase().trim();
	document.querySelectorAll('.product-card').forEach((card) => { card.hidden = query && !card.textContent.toLowerCase().includes(query); });
});
document.querySelector('.location strong').textContent = 'Hostel 7, Room 214';
document.querySelector('.shop-hero .eyebrow').nextElementSibling.nextElementSibling.textContent = document.body.classList.contains('pantry-page') ? 'Maggi, namkeen, cold drinks, and dorm-room saves delivered to Hostel 7 in 10–15 minutes.' : 'Toiletries, chargers, medicines, and last-minute supplies delivered to Hostel 7 in 8–12 minutes.';
document.querySelectorAll('.product-card').forEach((card) => { const name = card.querySelector('h3').textContent; const price = indianPrices[name]; if (price) { card.querySelector('strong').textContent = `₹${price.toFixed(2)}`; card.querySelector('.product-add').dataset.price = price; } });
function updateShopCart() { const count = storedItems.reduce((sum, item) => sum + item.quantity, 0); countEl.textContent = count; labelEl.textContent = `${count} item${count === 1 ? '' : 's'} in your bag`; localStorage.setItem('dashmate-items', JSON.stringify(storedItems)); }
document.querySelectorAll('.product-add').forEach((button) => button.addEventListener('click', () => { const item = storedItems.find((entry) => entry.name === button.dataset.name); if (button.dataset.added === 'true') { if (item) { item.quantity -= 1; if (item.quantity < 1) storedItems.splice(storedItems.indexOf(item), 1); } button.dataset.added = 'false'; button.textContent = '+ Add'; button.classList.remove('remove-product'); } else { if (item) item.quantity += 1; else storedItems.push({ name: button.dataset.name, price: Number(button.dataset.price), quantity: 1 }); button.dataset.added = 'true'; button.textContent = '− Remove'; button.classList.add('remove-product'); } updateShopCart(); }));
updateShopCart();
